workflows:
  ios_ipa_unsigned:
    name: iOS — Unsigned IPA (no codesign)
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Ensure iOS folder exists
        script: |
          if [ ! -d ios ]; then
            flutter create .
          fi

      - name: Set iOS bundle id & display name + min iOS
        script: |
          BUNDLE_ID=com.wesam.mda.pro
          DISPLAY_NAME="Market Data Pro"

          # تأكيد Info.plist موجود
          if [ ! -f ios/Runner/Info.plist ]; then
            echo "Missing ios/Runner/Info.plist"; exit 1
          fi

          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $DISPLAY_NAME" ios/Runner/Info.plist || true

          # ارفع الحد الأدنى إلى iOS 13
          plutil -replace MinimumOSVersion -string "13.0" ios/Runner/Info.plist || true
          sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/Podfile || true

      - name: Clean & install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build iOS (no codesign)
        script: |
          flutter clean
          flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        script: |
          rm -rf Payload Runner-unsigned.ipa
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          zip -r -9 Runner-unsigned.ipa Payload

    artifacts:
      - Runner-unsigned.ipa
