workflows:
  ios_ipa_unsigned:
    name: iOS — Unsigned IPA (no codesign)
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
    scripts:
      - name: Flutter pub get
        script: |
          set -e
          flutter pub get

      - name: Ensure iOS folder exists
        script: |
          set -e
          if [ ! -d ios ]; then
            flutter create .
          fi

      - name: Set identifiers + min iOS
        script: |
          set -e
          BUNDLE_ID=com.wesam.mda.pro
          DISPLAY_NAME="Market Data Pro"

          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $DISPLAY_NAME" ios/Runner/Info.plist || true
          plutil -replace MinimumOSVersion -string "13.0" ios/Runner/Info.plist || true

          # تأكيد iOS 13 في Podfile
          if grep -q "platform :ios" ios/Podfile; then
            sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/Podfile
          else
            echo "platform :ios, '13.0'" | cat - ios/Podfile > /tmp/Podfile && mv /tmp/Podfile ios/Podfile
          fi

      - name: Clean & install CocoaPods
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build iOS app (no codesign)
        script: |
          set -e
          flutter clean
          # يبني .app فقط بدون توقيع (بدون خطوة Archive)
          flutter build ios --release --no-codesign
          ls -la build/ios/iphoneos || true

      - name: Package to unsigned IPA
        script: |
          set -e
          APP_PATH="build/ios/iphoneos/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Runner.app not found under build/ios/iphoneos"
            exit 1
          fi
          rm -rf Payload Runner-unsigned.ipa
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -r Runner-unsigned.ipa Payload

    artifacts:
      - Runner-unsigned.ipa
