workflows:
  ios_ipa_unsigned:
    name: iOS — Unsigned IPA (archive, no codesign)
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
    scripts:
      - name: Flutter pub get
        script: |
          set -e
          flutter pub get

      - name: Ensure iOS folder exists
        script: |
          set -e
          if [ ! -d ios ]; then
            flutter create .
          fi

      - name: Set identifiers + iOS min version
        script: |
          set -e
          BUNDLE_ID=com.wesam.mda.pro
          DISPLAY_NAME="Market Data Pro"

          # Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $DISPLAY_NAME" ios/Runner/Info.plist || true
          plutil -replace MinimumOSVersion -string "13.0" ios/Runner/Info.plist || true

          # Podfile -> iOS 13
          if grep -q "platform :ios" ios/Podfile; then
            sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/Podfile
          else
            echo "platform :ios, '13.0'" | cat - ios/Podfile > /tmp/Podfile && mv /tmp/Podfile ios/Podfile
          fi

      - name: Clean & install CocoaPods
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      # نستخدم xcodebuild archive مع توقيع مُعطّل وباندل آي دي مضبوط
      - name: Archive with xcodebuild (no codesign)
        script: |
          set -e
          SCHEME="Runner"
          WORKSPACE="ios/Runner.xcworkspace"
          ARCHIVE_PATH="$PWD/build/ios/Runner.xcarchive"
          BUNDLE_ID="com.wesam.mda.pro"

          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$ARCHIVE_PATH" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            clean archive | xcpretty

      - name: Create unsigned IPA
        script: |
          set -e
          rm -rf Payload Runner-unsigned.ipa
          mkdir -p Payload
          APP_PATH="build/ios/Runner.xcarchive/Products/Applications/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Runner.app not found!"; ls -la build/ios; exit 1
          fi
          cp -R "$APP_PATH" Payload/
          zip -r -9 Runner-unsigned.ipa Payload

    artifacts:
      - Runner-unsigned.ipa
