workflows:
  ios_ipa_unsigned:
    name: iOS — Unsigned IPA (no codesign)
    environment:
      flutter: stable
      xcode: 15.4
    scripts:
      - name: Fix line endings (LF) for iOS scripts
        script: |
          set -e
          brew list dos2unix || brew install dos2unix
          find ios -type f -name "*.sh" -print0 | xargs -0 dos2unix || true
          dos2unix ios/Flutter/* || true
          dos2unix ios/Runner/* || true

      - name: Flutter clean & precache & deps
        script: |
          set -e
          flutter clean
          flutter precache --ios
          flutter pub get

      - name: Ensure iOS folder exists
        script: |
          if [ ! -d ios ]; then
            flutter create .
          fi

      - name: Install CocoaPods
        script: |
          set -e
          cd ios
          pod install --repo-update
          cd -

      # خيار 1 (المفضل): بناء IPA عبر Flutter بدون توقيع
      - name: Build IPA (Flutter, no codesign)
        script: |
          set -e
          flutter build ipa --release --no-codesign

      # خيار 2 (احتياطي): بناء بالأكسكود مباشرة بدون توقيع
      # - name: Archive with xcodebuild (NO codesign)
      #   script: |
      #     set -e
      #     xcodebuild -workspace ios/Runner.xcworkspace \
      #       -scheme Runner \
      #       -configuration Release \
      #       -sdk iphoneos \
      #       -destination 'generic/platform=iOS' \
      #       -archivePath build/Runner.xcarchive \
      #       DEVELOPMENT_TEAM= \
      #       CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_STYLE=Manual \
      #       archive

      - name: Package unsigned IPA (if using xcodebuild path)
        script: |
          set -e
          if [ -d "build/Runner.xcarchive/Products/Applications/Runner.app" ]; then
            rm -rf Payload
            mkdir -p Payload
            cp -R build/Runner.xcarchive/Products/Applications/Runner.app Payload/
            zip -r MarketDataAnalystPro-unsigned.ipa Payload
          fi

    artifacts:
      # ناتج Flutter
      - build/ios/ipa/*.ipa
      # لو استخدمت مسار xcodebuild
      - MarketDataAnalystPro-unsigned.ipa
