workflows:
  ios_ipa_unsigned:
    name: iOS — Unsigned IPA (no codesign)
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Ensure iOS folder exists
        script: flutter create .
      - name: Set iOS bundle id & display name
        script: |
          cd ios
          BUNDLE_ID="com.wesam.mda.pro"
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Market Data Pro" Runner/Info.plist || /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string Market Data Pro" Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleName Market Data Pro" Runner/Info.plist || /usr/libexec/PlistBuddy -c "Add :CFBundleName string Market Data Pro" Runner/Info.plist
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*;/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID};/g" Runner.xcodeproj/project.pbxproj
          cd ..
      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign
      - name: Package unsigned IPA (Payload root)
        script: |
          rm -rf Payload Runner-unsigned.ipa
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
          zip -r Runner-unsigned.ipa Payload
    artifacts:
      - Runner-unsigned.ipa