workflows:
  ios_unsigned_ipa:
    name: iOS — Unsigned IPA (no codesign)
    environment:
      flutter: stable
      xcode: 15.4
    scripts:
      - name: Flutter clean & deps
        script: |
          flutter clean
          flutter pub get

      - name: Ensure iOS folder exists
        script: |
          if [ ! -d ios ]; then
            flutter create .
          fi

      # (اختياري) اسم التطبيق والباكدج آي دي
      - name: Set bundle name/id
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Market Data Analyst Pro" ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.wesam.marketdata.pro" ios/Runner/Info.plist || true

      - name: Archive with xcodebuild (NO codesign)
        script: |
          set -e
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath build/Runner.xcarchive \
            DEVELOPMENT_TEAM= \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_STYLE=Manual \
            archive

      - name: Create unsigned IPA
        script: |
          set -e
          APP_PATH="build/Runner.xcarchive/Products/Applications/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Runner.app not found at $APP_PATH"
            ls -la build || true
            exit 1
          fi
          rm -rf Payload
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          cd Payload && zip -r ../MarketDataAnalystPro-unsigned.ipa . && cd ..

    artifacts:
      - MarketDataAnalystPro-unsigned.ipa
