workflows:
  ios_unsigned:
    name: iOS — Unsigned IPA (Flutter only)
    environment:
      flutter: stable
      xcode: 15.3
    scripts:
      - name: Patch Podfile + clean
        script: |
          set -ex
          # نضمن منصة iOS حديثة وننظف البودز
          if [ -f ios/Podfile ]; then
            sed -i '' "s/^platform :ios.*/platform :ios, '13.0'/" ios/Podfile || true
          fi
          rm -rf ios/Pods ios/Podfile.lock
          flutter clean
          flutter precache --ios
          flutter pub get

      - name: Install CocoaPods
        script: |
          set -ex
          cd ios
          pod repo update
          pod install
          cd -

      - name: Build IPA (Flutter, no codesign)
        script: |
          set -ex
          # بناء IPA بدون توقيع فقط عبر Flutter
          flutter build ipa --release --no-codesign -v

    artifacts:
      - build/ios/ipa/*.ipa
